### ISSUE TITLE
mod.request is not a function

### ISSUE THREAD

**Issue by apigeeks-paul** [messagemedia/messagemedia-rest-api-javascript-sdk#2]
Hi guys,

I'm trying to make a call with the javascript SDK from node js 7.10.1 with the following code:

```
var client = MessagemediaRestApi.ApiClient.instance;
var basic = client.authentications["basic"];

basic.username = user.MessageMediaUser;
basic.password = user.MessageMediaSecret;

var api = new MessagemediaRestApi.MessagingApi();
var post = new MessagemediaRestApi.Messages(mmMessages);

api.sendMessages(post, function (error, data, response) {
     ...
});
```
At the point `sendMessages` is called I get an exception `mod.request is not a function` with the following callstack:

```
at Request.request (/var/lib/arangodb3-apps/_db/nsw_justice/wyp_apis/APP/node_modules/superagent/lib/node/index.js:748:28)
2017-08-04T04:30:32Z [20466] ERROR     at Request.end (/var/lib/arangodb3-apps/_db/nsw_justice/wyp_apis/APP/node_modules/superagent/lib/node/index.js:868:18)
2017-08-04T04:30:32Z [20466] ERROR     at callApi (/var/lib/arangodb3-apps/_db/nsw_justice/wyp_apis/APP/node_modules/messagemedia-rest-api/src/ApiClient.js:405:13)
2017-08-04T04:30:32Z [20466] ERROR     at sendMessages (/var/lib/arangodb3-apps/_db/nsw_justice/wyp_apis/APP/node_modules/messagemedia-rest-api/src/api/MessagingApi.js:141:29)
```

Let it be known that I'm not the most worldly node developer, but, upon inspecting the superagent code it does seem a little crackers and I'd expect it not to work... but clearly it's working for you.
If you look at `superagent/lib/node/index.js` where the exception is occurring the offending line looks like this:

```
// initiate request
var mod = exports.protocols[url.protocol];

// request
var req = this.req = mod.request(options);
```

where `exports.protocls` has previously been defined as:
```
exports.protocols = {
  'http:': http,
  'https:': https
};

```

Do you guys have any insight into this?

**Comment by apigeeks-paul** [comment]
Ok, apologies for raising this. Turns out the code is being run in ArangoDb, which is a subset of node (I actually think it's an older io.js)... that is the problem.
